//Kirjaudutaan sisään ADMININA
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin.ad@example.fi",
  "password": "Admin123"
}

// Hanki ADMIN TOKEN
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "admin.ad@example.fi",
  "password": "Admin123"
}

// Hanki uusi ACCESS-TOKEN
POST http://localhost:3000/api/refresh-token

//Kirjaudutaan sisään
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "fake.admin@example.fi",
  "password": "FakeAdmin123"
}

// Hanki USER TOKEN
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "fake.admin@example.fi",
    "password": "FakeAdmin123"
}

// Tarkistetaan kirjautumisen tila
GET http://localhost:3000/auth/session

// Kirjaudu ulos
POST http://localhost:3000/auth/logout

// Luodaan uusi käyttäjä
POST http://localhost:3000/api/register
content-type: application/json

{
    "name": "Joonas",
    "email": "ad1224.jk@student.fi",
    "password": "Joonas123",
    "passwordConfirmation": "Joonas123"
}

// Päivitetään käyttäjän salasana
PUT http://localhost:3000/api/users/67e5721a616a079da974a449
Content-Type: application/json

{
    "password": "Salasana123"
}

// Päivitetään käyttäjän nimi
PUT http://localhost:3000/api/users/67e5721a616a079da974a449
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2VjNWJkNDcxMzM0OTY5OGI2Nzc0NGUiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFrZS5hZG1pbkBleGFtcGxlLmZpIiwiaWF0IjoxNzQzNTQ4MzU1LCJleHAiOjE3NDM1NTE5NTV9.5uK8gR8kaFqZCzySfim1fITb5oWPUF3Fh5gqu8vOARA

{
    "name": "OnnistunutTesti"
}

// Testataan sähköposti osoitteen duplikaatio virhe
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "virheTesti",
    "email": "testi.test@example.fi",
    "password": "salasana",
    "passwordConfirmation": "salasana"
}

// Kirjaudutaan käyttäjänä
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "testi.test@example.fi",
    "password": "Salasana123"
}

// Tarkastellaan kaikkia käyttäjiä (ADMIN oikeudet vaaditaan)
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2VjNTFkNDVhYWViODI2ZDYyZDkxMzEiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluLmFkQGV4YW1wbGUuZmkiLCJpYXQiOjE3NDM3MDU3MzEsImV4cCI6MTc0MzcwNTc5MX0.mj7rIDNmtQUHE7gv5hJpGJdzRoznqXntyg8egJOVkdY

// Luodaan albumi käyttäjänä
POST http://localhost:3000/api/albums
Content-Type: application/json

{
    "artist": "Tapani kansa",
    "title": "Kesän lapsi",
    "year": 1976,
    "genre": "Iskelmä",
    "tracks": 12
}

// Hae kaikki albumit
GET http://localhost:3000/api/albums

// LAJITTELE albumit VUOSILUVUN mukaan ja määritä järjestys
GET http://localhost:3000/api/albums?sortBy=year&order=asc
// LAJITTELE albumit ARTISTIN mukaan ja määritä järjestys
GET http://localhost:3000/api/albums?sortBy=artist&order=asc

// Hae albumit, joidenka JULKAISUVUOSI on SUUREMPI kuin ****
GET http://localhost:3000/api/albums?numericFilters=year>=1994

// Hae albumista VAIN artisti ja albumin nimi
GET http://localhost:3000/api/albums?fields=artist,title

// Hae albumi OSITTAISELLA artistin/albumin nimellä
GET http://localhost:3000/api/albums?search=tot

// Hae albumit YHDEN tai USEAMMAN GENREN perusteella
GET http://localhost:3000/api/albums?genre=Suomirock,Pop

// Hae albumi
GET http://localhost:3000/api/albums/67ec4f9c42e0ae9b679acf07

// Lisää uusi albumi
POST http://localhost:3000/api/albums
Content-Type: application/json

{
      "artist": "Testi",
      "title": "Joku",
      "year": 2001,
      "genre": "Iskelmä",
      "tracks": 13
}

// Päivitä albumi
PUT http://localhost:3000/api/albums/67aa42790cc9c81378a90cb5
Content-Type: application/json

{
    "title": "Imperiumin Vastaisku (Updated)",
    "genre": "AETOA ISKELMÄÄ"
}

// Poista albumi
DELETE http://localhost:3000/api/albums/67ec6263babb4435897a8ff7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2VjNTFkNDVhYWViODI2ZDYyZDkxMzEiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluLmFkQGV4YW1wbGUuZmkiLCJpYXQiOjE3NDM1NDg0NDQsImV4cCI6MTc0MzU1MjA0NH0.tPu8wDWIvL3kA8Y1dnJ20tqEFVEpeRZlHF0QnKuqHtw